server:
  host: "0.0.0.0"
  port: 8080

relays:
  - name: "Свет (не работает)"
    bcm_pin: 5
    phrase_on: "включи свет номер один"
    phrase_off: "выключи свет номер один"
  - name: "Свет на столе"
    bcm_pin: 17
    phrase_on: "включи свет номер два"
    phrase_off: "выключи свет номер два"
relays433:
  - name: "Свет у гаража"
    code_on: 16777200
    code_off: 16777201
    phrase_on: "включи свет номер один"
    phrase_off: "выключи свет номер один"
buttons:
  - name: "Light test button"
    bcm_pin: 26
    control_pin: 17
# dht11s:
#   - name: "Температура и влажность на столе"
#     bcm_pin: 22
#     phrase: "TODO какая температура"
dht22s:
  - name: "Температура и влажность на столе"
    bcm_pin: 22
    phrase: "TODO какая температура"
cameras:
  - id: 0
    name: "Камера на входе" 
    url: "rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=1.sdp?real_stream"

call_sign: "эй ты"